on: [push, pull_request_target]
name: Test and lint

jobs:

  install:
     - run: npm ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm test

  package_check:
    runs-on: ubuntu-latest
    steps:
      - name: "Ensure that code has been packaged and commited."
        run: |-
            npm install
            npm run

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@master

      - name: Install doctl
        uses: ./
        with:
          token: ${{ secrets.DIGITAL_OCEAN_API_TOKEN }}

      - name: Verify installation
        run: doctl version

      - name: Verify log-in
        run: doctl compute region list