name: Build and Deploy
on: [push]
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}} # server IP address
          key: ${{secrets.SSH_KEY}} # key for server
          username: ${{secrets.SSH_USERNAME}} # username for server

          script: |
            mkdir test
            cd test
            git clone git@github.com:cyberGuardianSeniorDesign/cyber-guardian-backend.git
            echo 'Successful deployment to Digital Ocean'