name: Build and Deploy
on: [push]
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        run:
            ssh -i ${{secrets.SSH_KEY}} ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}
            mkdir test
            cd test
            git clone git@github.com:cyberGuardianSeniorDesign/cyber-guardian-backend.git
            echo 'Successful deployment to Digital Ocean'