name: Build and Deploy to Admin
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app to admin
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }} # server IP address
          key: ${{ secrets.SSH_KEY }} # key for server
          username: ${{ secrets.SSH_USERNAME }} # username for server
          passphrase: ${{ secrets.ADMIN_PASSPHRASE }} # passphrase for admin side

          script: |
            cd ~/test
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts # gather SSH public keys from servers
            # git clone git@github.com:cyberGuardianSeniorDesign/cyber-guardian-backend.git
            git clone https://github.com/cyberGuardianSeniorDesign/cyber-guardian-backend.git
            echo 'Successful deployment to Digital Ocean'
