name: Build and Deploy to Admin

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ] 
  

jobs:
  deploy-to-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app to admin
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # server IP address
          key: ${{ secrets.SSH_KEY }} # key for server
          username: ${{ secrets.SSH_USERNAME }} # username for server
          passphrase: ${{ secrets.ADMIN_PASSPHRASE }} # passphrase for admin side

          script: |
            cd ~/test
            ssh-keyscan -H ${{ secrets.CLIENT_HOST }} > ~/.ssh/known_hosts # gather SSH public keys from servers
            rm -r cyber-guardian-backend
            echo 'Deleted old folder'
            # git clone backend:cyberGuardianSeniorDesign@cyber-guardian-backend.git
            git clone https://github.com/cyberGuardianSeniorDesign/cyber-guardian-backend.git
            rm -r ~/server/*
            mv -t ~/server/ ~/test/cyber-guardian-backend/*
            echo 'Moved to correct folder'
            echo 'Successful deployment to Digital Ocean'
            cd ~/server
            npm install --production
            echo 'Successfully installed node modules'