name: Build and Deploy to Client

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CLIENT_KEY }}
        with:
          host: ${{ secrets.CLIENT_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.CLIENT_KEY }}" > ~/.ssh/id_rsa
            host='github.com'
            hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
            ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
            git pull origin main
